### /credit/authorize
POST http://localhost:8080/credit/authorize
Content-Type: application/json

{
    "user": "hainet50b",
    "token": "4111110000001111",
    "amount": 1000
}

### /qr/create-code
POST http://localhost:8080/qr/create-code
Content-Type: application/json

{
  "user": "hainet50b",
  "amount": 1000
}
