### /credit/authorize
POST http://localhost:8080/credit/authorize
Content-Type: application/json

{
    "user": "hainet50b",
    "token": "4111110000001111",
    "amount": 1000
}

### /credit/authorize - INVALID_USER
POST http://localhost:8080/credit/authorize
Content-Type: application/json

{
  "user": "b59fc898-9e53-4307-9c57-eca214072aa8",
  "token": "4111110000001111",
  "amount": 1000
}

### /qr/create-code
POST http://localhost:8080/qr/create-code
Content-Type: application/json

{
  "user": "hainet50b",
  "amount": 1000
}

### /qr/create-code - INVALID_USER
POST http://localhost:8080/qr/create-code
Content-Type: application/json

{
  "user": "b59fc898-9e53-4307-9c57-eca214072aa8",
  "amount": 1000
}
