server:
  port: 8091
spring:
  application:
    name: qr-service
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
