server:
  port: 8070
spring:
  application:
    name: log-ingester
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:log-ingester
    username: sa
    password: ""
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        log-in-0:
          group: log-queue
management:
  endpoints:
    web:
      exposure:
        include: health
  #        include: health, prometheus
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
#    propagation:
#      type: w3c
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
