server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:log-ingester
    username: sa
    password: ""
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        log-in-0:
          group: log-queue
