server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_empty
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        log-in-0:
          group: log-queue
